language: bash

dist: bionic

before_install:
    - curl -sf https://test.docker.com | sh
    - docker --version
  
env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    - PLATFORMS=linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
  
stages:
  - name: test
    if: tag IS present OR branch = master
  - name: push
    if: tag IS present OR branch = master
  
script:
  - echo "$DOCKER_PASSWORD" | docker login -u sckyzo --password-stdin
  - docker run --privileged linuxkit/binfmt:v0.8
  - docker buildx create --use
  - docker buildx build
    --platform $PLATFORMS
    --build-arg "VERSION=$TRAVIS_TAG | cut -d '.' -f 1"
    --file "Dockerfile"
    --tag sckyzo/nextcloud_test:latest
    `if [ -n "$TRAVIS_TAG" ]; then echo "--tag sckyzo/nextcloud_test:$TRAVIS_TAG"; fi`
    `if [ -n "$TRAVIS_TAG" ]; then echo "--tag sckyzo/nextcloud_test:$VERSION"; fi`
    --push
    .
